//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.zfa_standardtypen.v02;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeldegrundDatenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeldegrundDatenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KdNr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}KdNrType"/>
 *         &lt;element name="DtErstUr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}DatumZeitMilliSecType" minOccurs="0"/>
 *         &lt;element name="DtErstAkt" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}DatumZeitMilliSecType"/>
 *         &lt;element name="MmMeld" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}MmMeldType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="testmerker" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}TestmerkerType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeldegrundDatenType", propOrder = {
    "kdNr",
    "dtErstUr",
    "dtErstAkt",
    "mmMeld"
})
public class MeldegrundDatenType {

    @XmlElement(name = "KdNr", required = true)
    protected String kdNr;
    @XmlElement(name = "DtErstUr")
    protected String dtErstUr;
    @XmlElement(name = "DtErstAkt", required = true)
    protected String dtErstAkt;
    @XmlElement(name = "MmMeld")
    @XmlSchemaType(name = "unsignedByte")
    protected short mmMeld;
    @XmlAttribute(name = "testmerker")
    protected TestmerkerType testmerker;

    /**
     * Gets the value of the kdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKdNr() {
        return kdNr;
    }

    /**
     * Sets the value of the kdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKdNr(String value) {
        this.kdNr = value;
    }

    /**
     * Gets the value of the dtErstUr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtErstUr() {
        return dtErstUr;
    }

    /**
     * Sets the value of the dtErstUr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtErstUr(String value) {
        this.dtErstUr = value;
    }

    /**
     * Gets the value of the dtErstAkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtErstAkt() {
        return dtErstAkt;
    }

    /**
     * Sets the value of the dtErstAkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtErstAkt(String value) {
        this.dtErstAkt = value;
    }

    /**
     * Gets the value of the mmMeld property.
     * 
     */
    public short getMmMeld() {
        return mmMeld;
    }

    /**
     * Sets the value of the mmMeld property.
     * 
     */
    public void setMmMeld(short value) {
        this.mmMeld = value;
    }

    /**
     * Gets the value of the testmerker property.
     * 
     * @return
     *     possible object is
     *     {@link TestmerkerType }
     *     
     */
    public TestmerkerType getTestmerker() {
        return testmerker;
    }

    /**
     * Sets the value of the testmerker property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestmerkerType }
     *     
     */
    public void setTestmerker(TestmerkerType value) {
        this.testmerker = value;
    }

}
