//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.zfa_standardtypen.v02;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv_bund.zfa.zfa_standardtypen.v02 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MeldegrundDaten_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "MeldegrundDaten");
    private final static QName _MitteilungspflichtigenDaten_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "MitteilungspflichtigenDaten");
    private final static QName _Inlandsadresse_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "Inlandsadresse");
    private final static QName _FehlerDaten_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "FehlerDaten");
    private final static QName _Auslandsadresse_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "Auslandsadresse");
    private final static QName _UebermittelndeStelleDaten_QNAME = new QName("http://www.zfa.drv-bund.de/zfa_standardtypen/v02", "UebermittelndeStelleDaten");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv_bund.zfa.zfa_standardtypen.v02
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FehlerDatenFachlichType }
     * 
     */
    public FehlerDatenFachlichType createFehlerDatenFachlichType() {
        return new FehlerDatenFachlichType();
    }

    /**
     * Create an instance of {@link MipfDatenType }
     * 
     */
    public MipfDatenType createMipfDatenType() {
        return new MipfDatenType();
    }

    /**
     * Create an instance of {@link UebermittelndeStelleDatenType }
     * 
     */
    public UebermittelndeStelleDatenType createUebermittelndeStelleDatenType() {
        return new UebermittelndeStelleDatenType();
    }

    /**
     * Create an instance of {@link InlandsadresseType }
     * 
     */
    public InlandsadresseType createInlandsadresseType() {
        return new InlandsadresseType();
    }

    /**
     * Create an instance of {@link AuslandsadresseType }
     * 
     */
    public AuslandsadresseType createAuslandsadresseType() {
        return new AuslandsadresseType();
    }

    /**
     * Create an instance of {@link MeldegrundDatenType }
     * 
     */
    public MeldegrundDatenType createMeldegrundDatenType() {
        return new MeldegrundDatenType();
    }

    /**
     * Create an instance of {@link PostfachadresseType }
     * 
     */
    public PostfachadresseType createPostfachadresseType() {
        return new PostfachadresseType();
    }

    /**
     * Create an instance of {@link AllgAdresseType }
     * 
     */
    public AllgAdresseType createAllgAdresseType() {
        return new AllgAdresseType();
    }

    /**
     * Create an instance of {@link GrosskundenadresseType }
     * 
     */
    public GrosskundenadresseType createGrosskundenadresseType() {
        return new GrosskundenadresseType();
    }

    /**
     * Create an instance of {@link UeStPostfachadresseType }
     * 
     */
    public UeStPostfachadresseType createUeStPostfachadresseType() {
        return new UeStPostfachadresseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeldegrundDatenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "MeldegrundDaten")
    public JAXBElement<MeldegrundDatenType> createMeldegrundDaten(MeldegrundDatenType value) {
        return new JAXBElement<MeldegrundDatenType>(_MeldegrundDaten_QNAME, MeldegrundDatenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MipfDatenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "MitteilungspflichtigenDaten")
    public JAXBElement<MipfDatenType> createMitteilungspflichtigenDaten(MipfDatenType value) {
        return new JAXBElement<MipfDatenType>(_MitteilungspflichtigenDaten_QNAME, MipfDatenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlandsadresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "Inlandsadresse")
    public JAXBElement<InlandsadresseType> createInlandsadresse(InlandsadresseType value) {
        return new JAXBElement<InlandsadresseType>(_Inlandsadresse_QNAME, InlandsadresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FehlerDatenFachlichType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "FehlerDaten")
    public JAXBElement<FehlerDatenFachlichType> createFehlerDaten(FehlerDatenFachlichType value) {
        return new JAXBElement<FehlerDatenFachlichType>(_FehlerDaten_QNAME, FehlerDatenFachlichType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuslandsadresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "Auslandsadresse")
    public JAXBElement<AuslandsadresseType> createAuslandsadresse(AuslandsadresseType value) {
        return new JAXBElement<AuslandsadresseType>(_Auslandsadresse_QNAME, AuslandsadresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UebermittelndeStelleDatenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", name = "UebermittelndeStelleDaten")
    public JAXBElement<UebermittelndeStelleDatenType> createUebermittelndeStelleDaten(UebermittelndeStelleDatenType value) {
        return new JAXBElement<UebermittelndeStelleDatenType>(_UebermittelndeStelleDaten_QNAME, UebermittelndeStelleDatenType.class, null, value);
    }

}
