//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zfa.drv-bund.de/zfa_standardtypen/v02", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.drv_bund.zfa.zfa_standardtypen.v02;
