//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.rebsy.rentenbezugsmitteilung.mz01v02;

import model.BaseEntity;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LeistungsbetragType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LeistungsbetragType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LeRg" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}MerkmalRechtsgrundLeistungType"/>
 *         &lt;element name="LeBtr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}BetragSignedType"/>
 *         &lt;element name="LeBtrNach" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}BetragUnsignedType" minOccurs="0"/>
 *         &lt;element name="Garantierente" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}GarantierenteType" minOccurs="0"/>
 *         &lt;element name="Versorgungsfreibetrag" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}VersorgungsfreibetragType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeistungsbetragType", propOrder = {
    "leRg",
    "leBtr",
    "leBtrNach",
    "garantierente",
    "versorgungsfreibetrag",
    "daten"
})
public class LeistungsbetragType extends BaseEntity {

    @XmlElement(name = "LeRg", required = true)
    protected String leRg;
    @XmlElement(name = "LeBtr", required = true)
    protected String leBtr;
    @XmlElement(name = "LeBtrNach")
    protected String leBtrNach;
    @ManyToOne
    @JoinColumn(name = "fk_garantierente")
    @XmlElement(name = "Garantierente")
    protected GarantierenteType garantierente;
    @ManyToOne
    @JoinColumn(name = "fk_versorgungsfreibetrag")
    @XmlElement(name = "Versorgungsfreibetrag")
    protected VersorgungsfreibetragType versorgungsfreibetrag;


    @ManyToOne
    @JoinColumn(name = "fk_daten_id", nullable = true)
    Daten daten;

    /**
     * Gets the value of the leRg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeRg() {
        return leRg;
    }

    /**
     * Sets the value of the leRg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeRg(String value) {
        this.leRg = value;
    }

    /**
     * Gets the value of the leBtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeBtr() {
        return leBtr;
    }

    /**
     * Sets the value of the leBtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeBtr(String value) {
        this.leBtr = value;
    }

    /**
     * Gets the value of the leBtrNach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeBtrNach() {
        return leBtrNach;
    }

    /**
     * Sets the value of the leBtrNach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeBtrNach(String value) {
        this.leBtrNach = value;
    }

    /**
     * Gets the value of the garantierente property.
     * 
     * @return
     *     possible object is
     *     {@link GarantierenteType }
     *     
     */
    public GarantierenteType getGarantierente() {
        return garantierente;
    }

    /**
     * Sets the value of the garantierente property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarantierenteType }
     *     
     */
    public void setGarantierente(GarantierenteType value) {
        this.garantierente = value;
    }

    /**
     * Gets the value of the versorgungsfreibetrag property.
     * 
     * @return
     *     possible object is
     *     {@link VersorgungsfreibetragType }
     *     
     */
    public VersorgungsfreibetragType getVersorgungsfreibetrag() {
        return versorgungsfreibetrag;
    }

    /**
     * Sets the value of the versorgungsfreibetrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersorgungsfreibetragType }
     *     
     */
    public void setVersorgungsfreibetrag(VersorgungsfreibetragType value) {
        this.versorgungsfreibetrag = value;
    }

}
