//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.rebsy.rentenbezugsmitteilung.mz01v02;

import business.ConverterUtility;
import model.BaseEntity;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


/**
 * <p>Java class for VersorgungsfreibetragType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersorgungsfreibetragType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VfbDtEinw" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}BemessungsgrundlageDatumEinwilligungType"/>
 *         &lt;element name="VfbBmg" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v02}BetragSignedType"/>
 *         &lt;element name="VfbJahr" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}BemessungsgrundlageJahrType"/>
 *         &lt;element name="VfbBeginn" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}MonatType" minOccurs="0"/>
 *         &lt;element name="VfbEnde" type="{http://www.zfa.drv-bund.de/rebsy/rentenbezugsmitteilung/mz01v02}MonatType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersorgungsfreibetragType", propOrder = {
    "vfbDtEinw",
    "vfbBmg",
    "vfbJahr",
    "vfbBeginn",
    "vfbEnde"
})
public class VersorgungsfreibetragType extends BaseEntity {

    @Transient
    @XmlElement(name = "VfbDtEinw", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vfbDtEinw;
    @XmlElement(name = "VfbBmg", required = true)
    protected String vfbBmg;
    @Transient
    @XmlElement(name = "VfbJahr", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar vfbJahr;
    @XmlElement(name = "VfbBeginn")
    protected String vfbBeginn;
    @XmlElement(name = "VfbEnde")
    protected String vfbEnde;

    @Basic
    @Access(AccessType.PROPERTY)
    @Column(name = "vfbDtEinw")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDateVfbDtEinw() {
        return ConverterUtility.convertToDate(vfbDtEinw);
    }

    public void setDateVfbDtEinw(Date date) { setVfbDtEinw(ConverterUtility.convertToXmlGregCal(date)); }

    @Basic
    @Access(AccessType.PROPERTY)
    @Column(name = "vfbJahr")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDateVfbJahr() {
        return ConverterUtility.convertToDate(vfbJahr);
    }

    public void setDateVfbJahr(Date date) { setVfbJahr(ConverterUtility.convertToXmlGregCal(date)); }
    /**
     * Gets the value of the vfbDtEinw property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVfbDtEinw() {
        return vfbDtEinw;
    }

    /**
     * Sets the value of the vfbDtEinw property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVfbDtEinw(XMLGregorianCalendar value) {
        this.vfbDtEinw = value;
    }

    /**
     * Gets the value of the vfbBmg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVfbBmg() {
        return vfbBmg;
    }

    /**
     * Sets the value of the vfbBmg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVfbBmg(String value) {
        this.vfbBmg = value;
    }

    /**
     * Gets the value of the vfbJahr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVfbJahr() {
        return vfbJahr;
    }

    /**
     * Sets the value of the vfbJahr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVfbJahr(XMLGregorianCalendar value) {
        this.vfbJahr = value;
    }

    /**
     * Gets the value of the vfbBeginn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVfbBeginn() {
        return vfbBeginn;
    }

    /**
     * Sets the value of the vfbBeginn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVfbBeginn(String value) {
        this.vfbBeginn = value;
    }

    /**
     * Gets the value of the vfbEnde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVfbEnde() {
        return vfbEnde;
    }

    /**
     * Sets the value of the vfbEnde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVfbEnde(String value) {
        this.vfbEnde = value;
    }

}
