//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.zfa_standardtypen.v03;

import model.BaseEntity;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuftragnehmerDatenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuftragnehmerDatenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WIdNr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}WIdNrType" minOccurs="0"/>
 *         &lt;element name="StNr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}StNrType" minOccurs="0"/>
 *         &lt;element name="KdNr" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}KdNrType"/>
 *         &lt;element name="Bez" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}BezType"/>
 *         &lt;element name="AnName" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}AnNameType" minOccurs="0"/>
 *         &lt;element name="AnTel" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}TelType" minOccurs="0"/>
 *         &lt;element name="AnDurchwahl" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}DurchwahlType" minOccurs="0"/>
 *         &lt;element name="AnMail" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}EmailType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Inlandsadresse" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}InlandsadresseType"/>
 *           &lt;element name="Auslandsadresse" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}AuslandsadresseType"/>
 *           &lt;element name="Postfachadresse" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}PostfachadresseType"/>
 *           &lt;element name="Grosskundenadresse" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}GrosskundenadresseType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity(name="AuftragnehmerDatenType3")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuftragnehmerDatenType", propOrder = {
    "wIdNr",
    "stNr",
    "kdNr",
    "bez",
    "anName",
    "anTel",
    "anDurchwahl",
    "anMail",
    "inlandsadresse",
    "auslandsadresse",
    "postfachadresse",
    "grosskundenadresse"
})
public class AuftragnehmerDatenType extends BaseEntity {

    @XmlElement(name = "WIdNr")
    protected String wIdNr;
    @XmlElement(name = "StNr")
    protected String stNr;
    @XmlElement(name = "KdNr", required = true)
    protected String kdNr;
    @XmlElement(name = "Bez", required = true)
    protected String bez;
    @XmlElement(name = "AnName")
    protected String anName;
    @XmlElement(name = "AnTel")
    protected String anTel;
    @XmlElement(name = "AnDurchwahl")
    protected String anDurchwahl;
    @XmlElement(name = "AnMail")
    protected String anMail;
    @ManyToOne
    @JoinColumn(name ="fk_AuftragnehmerDaten")
    @XmlElement(name = "Inlandsadresse")
    protected InlandsadresseType inlandsadresse;
    @ManyToOne
    @JoinColumn(name ="fk_auslandsadresse")
    @XmlElement(name = "Auslandsadresse")
    protected AuslandsadresseType auslandsadresse;
    @ManyToOne
    @JoinColumn(name ="fk_postfachadresse")
    @XmlElement(name = "Postfachadresse")
    protected PostfachadresseType postfachadresse;
    @ManyToOne
    @JoinColumn(name = "fk_postfachadressetype")
    @XmlElement(name = "Grosskundenadresse")
    protected GrosskundenadresseType grosskundenadresse;

    /**
     * Gets the value of the wIdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWIdNr() {
        return wIdNr;
    }

    /**
     * Sets the value of the wIdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWIdNr(String value) {
        this.wIdNr = value;
    }

    /**
     * Gets the value of the stNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStNr() {
        return stNr;
    }

    /**
     * Sets the value of the stNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStNr(String value) {
        this.stNr = value;
    }

    /**
     * Gets the value of the kdNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKdNr() {
        return kdNr;
    }

    /**
     * Sets the value of the kdNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKdNr(String value) {
        this.kdNr = value;
    }

    /**
     * Gets the value of the bez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBez() {
        return bez;
    }

    /**
     * Sets the value of the bez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBez(String value) {
        this.bez = value;
    }

    /**
     * Gets the value of the anName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnName() {
        return anName;
    }

    /**
     * Sets the value of the anName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnName(String value) {
        this.anName = value;
    }

    /**
     * Gets the value of the anTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnTel() {
        return anTel;
    }

    /**
     * Sets the value of the anTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnTel(String value) {
        this.anTel = value;
    }

    /**
     * Gets the value of the anDurchwahl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnDurchwahl() {
        return anDurchwahl;
    }

    /**
     * Sets the value of the anDurchwahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnDurchwahl(String value) {
        this.anDurchwahl = value;
    }

    /**
     * Gets the value of the anMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnMail() {
        return anMail;
    }

    /**
     * Sets the value of the anMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnMail(String value) {
        this.anMail = value;
    }

    /**
     * Gets the value of the inlandsadresse property.
     * 
     * @return
     *     possible object is
     *     {@link InlandsadresseType }
     *     
     */
    public InlandsadresseType getInlandsadresse() {
        return inlandsadresse;
    }

    /**
     * Sets the value of the inlandsadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlandsadresseType }
     *     
     */
    public void setInlandsadresse(InlandsadresseType value) {
        this.inlandsadresse = value;
    }

    /**
     * Gets the value of the auslandsadresse property.
     * 
     * @return
     *     possible object is
     *     {@link AuslandsadresseType }
     *     
     */
    public AuslandsadresseType getAuslandsadresse() {
        return auslandsadresse;
    }

    /**
     * Sets the value of the auslandsadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuslandsadresseType }
     *     
     */
    public void setAuslandsadresse(AuslandsadresseType value) {
        this.auslandsadresse = value;
    }

    /**
     * Gets the value of the postfachadresse property.
     * 
     * @return
     *     possible object is
     *     {@link PostfachadresseType }
     *     
     */
    public PostfachadresseType getPostfachadresse() {
        return postfachadresse;
    }

    /**
     * Sets the value of the postfachadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostfachadresseType }
     *     
     */
    public void setPostfachadresse(PostfachadresseType value) {
        this.postfachadresse = value;
    }

    /**
     * Gets the value of the grosskundenadresse property.
     * 
     * @return
     *     possible object is
     *     {@link GrosskundenadresseType }
     *     
     */
    public GrosskundenadresseType getGrosskundenadresse() {
        return grosskundenadresse;
    }

    /**
     * Sets the value of the grosskundenadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrosskundenadresseType }
     *     
     */
    public void setGrosskundenadresse(GrosskundenadresseType value) {
        this.grosskundenadresse = value;
    }

}
