//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.zfa_standardtypen.v03;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeschlechtType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GeschlechtType">
 *   &lt;restriction base="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}String.Latin">
 *     &lt;length value="1"/>
 *     &lt;enumeration value="w"/>
 *     &lt;enumeration value="m"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GeschlechtType")
@XmlEnum
public enum GeschlechtType {

    @XmlEnumValue("w")
    W("w"),
    @XmlEnumValue("m")
    M("m");
    private final String value;

    GeschlechtType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GeschlechtType fromValue(String v) {
        for (GeschlechtType c: GeschlechtType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
