//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.zfa_standardtypen.v03;

import model.BaseEntity;

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostfachadresseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostfachadresseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Postfach" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}PostfachType"/>
 *         &lt;element name="PostfachOrt" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}OrtType"/>
 *         &lt;element name="PostfachPlz" type="{http://www.zfa.drv-bund.de/zfa_standardtypen/v03}PLZType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity(name ="PostfachadresseType3")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostfachadresseType", propOrder = {
    "postfach",
    "postfachOrt",
    "postfachPlz"
})
public class PostfachadresseType extends BaseEntity {

    @XmlElement(name = "Postfach")
    @XmlSchemaType(name = "positiveInteger")
    protected int postfach;
    @XmlElement(name = "PostfachOrt", required = true)
    protected String postfachOrt;
    @XmlElement(name = "PostfachPlz", required = true)
    protected String postfachPlz;

    /**
     * Gets the value of the postfach property.
     * 
     */
    public int getPostfach() {
        return postfach;
    }

    /**
     * Sets the value of the postfach property.
     * 
     */
    public void setPostfach(int value) {
        this.postfach = value;
    }

    /**
     * Gets the value of the postfachOrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostfachOrt() {
        return postfachOrt;
    }

    /**
     * Sets the value of the postfachOrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostfachOrt(String value) {
        this.postfachOrt = value;
    }

    /**
     * Gets the value of the postfachPlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostfachPlz() {
        return postfachPlz;
    }

    /**
     * Sets the value of the postfachPlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostfachPlz(String value) {
        this.postfachPlz = value;
    }

}
