//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.19 at 03:20:07 PM CET 
//


package de.drv_bund.zfa.rebsy.rentenbezugsmitteilung.mz01v04;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv_bund.zfa.rebsy.rentenbezugsmitteilung.mz01v04 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv_bund.zfa.rebsy.rentenbezugsmitteilung.mz01v04
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Daten }
     * 
     */
    public Daten createDaten() {
        return new Daten();
    }

    /**
     * Create an instance of {@link MeldegrundDatenMZ01Type }
     * 
     */
    public MeldegrundDatenMZ01Type createMeldegrundDatenMZ01Type() {
        return new MeldegrundDatenMZ01Type();
    }

    /**
     * Create an instance of {@link LeistungsempfaengerDatenMZ01Type }
     * 
     */
    public LeistungsempfaengerDatenMZ01Type createLeistungsempfaengerDatenMZ01Type() {
        return new LeistungsempfaengerDatenMZ01Type();
    }

    /**
     * Create an instance of {@link BezugsDatenType }
     * 
     */
    public BezugsDatenType createBezugsDatenType() {
        return new BezugsDatenType();
    }

    /**
     * Create an instance of {@link LeistungsbetragType }
     * 
     */
    public LeistungsbetragType createLeistungsbetragType() {
        return new LeistungsbetragType();
    }

    /**
     * Create an instance of {@link VorzeitraeumeType }
     * 
     */
    public VorzeitraeumeType createVorzeitraeumeType() {
        return new VorzeitraeumeType();
    }

    /**
     * Create an instance of {@link BeitragsDatenType }
     * 
     */
    public BeitragsDatenType createBeitragsDatenType() {
        return new BeitragsDatenType();
    }

    /**
     * Create an instance of {@link GarantierenteType }
     * 
     */
    public GarantierenteType createGarantierenteType() {
        return new GarantierenteType();
    }

    /**
     * Create an instance of {@link VersorgungsfreibetragType }
     * 
     */
    public VersorgungsfreibetragType createVersorgungsfreibetragType() {
        return new VersorgungsfreibetragType();
    }

}
